### ISSUE TITLE
[V3] Used named import for `fast-xml-parser`

### ISSUE THREAD

**Issue by andipaetzold** [andipaetzold/mdb-reader#170]
See https://github.com/andipaetzold/mdb-reader/pull/169

**Comment by ellis2323** [comment]
Thx for your help,

I will upgrade to 14.19 all the same.

**Comment by andipaetzold** [comment]
@ellis2323 This is just a ticket I created so I won't forget to revert today's change in 2023 when I drop node 14 support.

The latest version of `mdb-reader` (2.1.1) should also fix your problem. I just closed your ticket: https://github.com/andipaetzold/mdb-reader/issues/168
