### ISSUE TITLE
Encoding Problem

### ISSUE THREAD

**Issue by ellis2323** [andipaetzold/mdb-reader#172]
I have a french MDB, using probably not an UTF-8 encoding. If I read the table 'tTour', i see:
```
{ NoTour: 1, NomTour: 'Engagement' }
{ NoTour: 2, NomTour: 'S�rie' }
{ NoTour: 3, NomTour: '16�me f.' }
{ NoTour: 4, NomTour: '8�me f.' }
{ NoTour: 5, NomTour: 'Quart f.' }
{ NoTour: 6, NomTour: 'Semi f.' }
{ NoTour: 7, NomTour: 'Finale'
```

I suspect an iso8859-15.

the mdb source:
https://u.pcloud.link/publink/show?code=XZnIlkVZLG3ffaEEef4XDRskx2F5qyBGbHYV

Is there an option to set the encoding source ?

**Comment by andipaetzold** [comment]
Hey @ellis2323,

Ideally, the library should handle the encodings correctly and you won't need to specify an encoding.
I'll take a look :eyes: Thanks for providing the database :)

**Comment by andipaetzold** [comment]
I just released a new version that should fix your issue. There was a general issue with non-ascii characters.
