### ISSUE TITLE
[browser] Use of operator ?? and ?.

### ISSUE THREAD

**Issue by ellis2323** [andipaetzold/mdb-reader#197]
Hello,

Currently, I'm trying to integrate mdb-reader in a vue application (vue2 with vuetify) and I encounter some issues because you use the ?? and ?. operators. These operators are pretty recent and not supported in many browser. Is it really needed in this library.

Best regards,

**Comment by andipaetzold** [comment]
Hey 👋 

unfortunately, that's not easily possible.

`mdb-reader` uses three features that were introduced in ECMAScript 2020:
* Nullish coalescing
* Optional chaining
* BigInt

Nullish coalescing & optional chaining can be transpiled to an earlier version of ECMAScript. This doesn't work for BigInt as a transpilation would change it's functionality. Even if I transpiled optional chaining & nullish coalescing, you would probably see other warnings about BigInt.

If you don't need to read data with BigInt or DateTimeExtended or don't read encrypted databases, you can use `mdb-reader` v1 instead. v1 targets ES2018 and you shouldn't run into these issues anymore. There are no big interface changes compared to v2 and you should only need to update your dependencies.

**Comment by ellis2323** [comment]
Hi,

Ok, I understand. To use mdb-reader in my projet, I add in vue.config.js:
`
const webpack = require('webpack')
const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  configureWebpack: {
    plugins: [
      new webpack.ProvidePlugin({
        Buffer: ["buffer", "Buffer"],
      }),
    ],
    resolve: {
      fallback: {
        stream: require.resolve("stream-browserify"),
        buffer: require.resolve("buffer")
      },
      alias: {
        "buffer": "buffer",
        "stream": "stream-browserify"
      }
    },
  },
  transpileDependencies: [
    'vuetify'
  ]
})
`

**Comment by andipaetzold** [comment]
Do you receive the error during compilation? If yes, you could transpile it or find another fix as you are not the first person running into issues with optional chaining/nullish coalescing and webpack.

Is otherwise using mdb-reader v1 a valid option?

I currently don't plan to release an update for this.

**Comment by ellis2323** [comment]
With the config files, there's no problem. You can close this ticket. v1 was not a valid option since I used european encodings.
