### ISSUE TITLE
Uncaught RangeError: offset is not uint

### ISSUE THREAD

**Issue by sspa-dhayes** [andipaetzold/mdb-reader#207]
When I try to load this using the Browser example, I get:
       
Uncaught RangeError: offset is not uint
    at checkOffset (index.js:1097:1)
    at Uint8Array.readInt32LE (index.js:1220:1)
    at readComplexOrLong (complexOrLong.js:2:1)
    at readFieldValue (index.js:43:1)
    at Table.getDataFromPage (Table.js:242:1)
    at Table.getData (Table.js:132:1)
    at new MDBReader (MDBReader.js:15:1)

**Comment by andipaetzold** [comment]
👋 

Could you share a database where you run into this issue so I can reproduce it? Ideally, remove all unrelated data or create the database from scratch to avoid publishing potentially sensitive information.

**Comment by sspa-dhayes** [comment]
Hi Andi,

It seems to be with all databases i use.   I just went down the rabbit  hole and i think it might be a webpack dependency issue in react using an old buffer library.   lets close this one and see if i can sort it out.

**Comment by andipaetzold** [comment]
👍  Feel free to reopen if it turns out not to be webpack-specific. Best way to test is probably using Node directly as you don't need to polyfill `Buffer` there. There are also some databases in this repo that should definitely work.

**Comment by mnappo** [comment]
Any small generic database will cause this error for me using webpack/create-react-app. In my node_modules folder I see that the current version of buffer (installed with npm i buffer) has the default zero. When I build and deploy though, the buffer included is node-libs-browser/node_modules/buffer. Any suggestions here would be helpful - I will update if I manage to solve it.

I think this is also the same issue as #213
