### ISSUE TITLE
Unable to import the package in Nestjs

### ISSUE THREAD

**Issue by Arya-Aghaei** [andipaetzold/mdb-reader#235]
Hi, I am trying to use this awesome package in Nestjs, but I receive this error, please help to solve this issue, thank you in advance.

`const mdb_reader_1 = require("mdb-reader").default;
                     ^
Error [ERR_REQUIRE_ESM]: require() of ES Module E:\api\node_modules\mdb-reader\lib\node\index.js from E:\api\dist\workshop\workshop.service.js not supported.
Instead change the require of index.js in E:\api\dist\workshop\workshop.service.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (E:\api\dist\workshop\workshop.service.js:12:22)
    at Object.<anonymous> (E:\api\dist\workshop\workshop.module.js:11:28)
    at Object.<anonymous> (E:\api\dist\app.module.js:17:27)
    at Object.<anonymous> (E:\api\dist\main.js:4:22)
    `

**Comment by andipaetzold** [comment]
Hey @Arya-Aghaei ,

this package is currently a pure ESM package. Please have a look at this: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c. I hope you can resolve your issue that way.
