### ISSUE TITLE
can not compile when my typescript version is  3.1.6

### ISSUE THREAD

**Issue by liujiusheng** [andipaetzold/mdb-reader#247]
"typescript": "^3.1.6"

![image](https://user-images.githubusercontent.com/9045263/188614764-484d78d6-766d-4538-a3c1-e85bc12cd885.png)

**Comment by andipaetzold** [comment]
Hey,

TypeScript 3.1 doesn't seem to be compatible with the type definitions used by the library.
That TypeScript version is almost 4 years old and probably struggles with other libraries as well. I'd recommend updating to the latest version.
