### ISSUE TITLE
Data loss for string fields over 1893 characters

### ISSUE THREAD

**Issue by shelley-xyris** [andipaetzold/mdb-reader#281]
Fields that contain over ~1893 characters are getting cut very short, returning a string that somewhat resembles what should have been returned. For example, if the long string started with "Version 1 ... " followed by large amounts of text, its returning "Versgr " and nothing else

**Comment by andipaetzold** [comment]
The bug should be fixed in the latest release (2.2.6).

**Comment by shelley-xyris** [comment]
> The bug should be fixed in the latest release (2.2.6).

Working perfectly! Great work, thank you for the quick response.
