### ISSUE TITLE
Security: upgrade package fast-xml-parser

### ISSUE THREAD

**Issue by AnhTuanGU** [andipaetzold/mdb-reader#294]
Hi, 
Currently, I am using  [mdb-reader](https://github.com/andipaetzold/mdb-reader) in the project, and after setting up Dependabot I receive an alert for a security [issue](https://github.com/NaturalIntelligence/fast-xml-parser/security/advisories/GHSA-6w63-h3fj-q4vw) that related to package `fast-xml-parser`. Can you update package `fast-xml-parser` to version 4.2.4?

**Comment by andipaetzold** [comment]
👋 

The package depends on `fast-xml-parser: ^4.0.0`. The patched version 4.2.4 is included in that version range, so an update of `mdb-reader` is not required.

You should be able to update `fast-xml-parser` in your project by running `npm update fast-xml-parser`.
