### ISSUE TITLE
Password protected mdb files

### ISSUE THREAD

**Issue by zatkhahi** [andipaetzold/mdb-reader#90]
How to read password protected mdb files? Does your library support this or any clue to add this capability?

**Comment by andipaetzold** [comment]
Hey @zatkhahi,

it is currently not possible to read password-protected files using this library. But I am happy to try implementing this feature.

**Comment by andipaetzold** [comment]
Hey @zatkhahi,

can you check the latest version of `mdb-reader`. The package is now able to decrypt a couple of different encryptions. All encrypted `.mdb` files should be supported. If not, feel free to reopen the ticket, and please provide a sample database.
